"""Add nutrition and user profile fields

Revision ID: ad387cb0666b
Revises: 2b0b263c5fa7
Create Date: 2026-06-07 18:52:57.834815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad387cb0666b'
down_revision: Union[str, Sequence[str], None] = '2b0b263c5fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('calories', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('proteins', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('fats', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('carbohydrates', sa.Float(), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'allergens',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'allergens',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('products', 'carbohydrates')
    op.drop_column('products', 'fats')
    op.drop_column('products', 'proteins')
    op.drop_column('products', 'calories')
    # ### end Alembic commands ###
