"""Add nutrition and user profile fields

Revision ID: e01e91952eab
Revises: ad387cb0666b
Create Date: 2026-06-07 18:56:13.730907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e01e91952eab'
down_revision: Union[str, Sequence[str], None] = 'ad387cb0666b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('calories', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('proteins', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('fats', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('carbohydrates', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('dietary_preference', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('allergens', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('xp_points', sa.Integer(), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'xp_points')
    op.drop_column('users', 'is_premium')
    op.drop_column('users', 'allergens')
    op.drop_column('users', 'dietary_preference')
    op.drop_column('products', 'carbohydrates')
    op.drop_column('products', 'fats')
    op.drop_column('products', 'proteins')
    op.drop_column('products', 'calories')
    # ### end Alembic commands ###
